version: "3.7"

services:
  app:
    image: node:lts
    command: npm install -g nodemon
    command: node script.js
    ports:
      - 3000:3000
    working_dir: /node_lessons
    volumes:
        - ./:/node_lessons